### ISSUE TITLE
需要登录验证的爬虫问题

### ISSUE THREAD

**Issue by clementine07** [leizongmin/book-crawler-mysql-cron#8]
您好，因为我参加学校的一个小项目，然后需要一些数据，看到您的爬虫教程。但是有些其他细节问题想问您。
1.如果我想做一个需要登录验证才能获取的数据html页面（从教务处内获取课程表），请问怎么爬取呢？（如果不登录，是否能爬去所有学生的课程表）
2.需要爬去一个公众号的历史消息记录，还有详情，但是我网页打开历史记录提示（请在微信客户端打开链接。）该如何避免这个提示，获取所有历史记录。

**Comment by leizongmin** [comment]
- 1、如果网站需要登录验证，一般都是通过`cookies`来记录的，因此可以先在浏览器上登录你的帐号，然后通过浏览器自带的调试工具取出你的`cookies`信息，在 Node.js 程序使用`request()`发送请求时，带上该`cookies`即可。
- 2、爬取微信公众号文章方法与上面类似，但可能受到微信方面更多的限制，难度会稍增加。具体我没做过。
